version: '19.03.13'

services:
  codrr_pg:
    image: postgres:15.0
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: codrrdb
      POSTGRES_USER: ucoderr
      POSTGRES_PASSWORD: ucoderr
    volumes:
      - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
      